server:
  port: 30120
  shutdown: graceful

spring:
  rabbitmq:
    host: localhost
    port: 25672
    username: test_user
    password: test

  redis:
    host: localhost
    port: 26379

  cloud:
    function:
      definition: defaultBroadcastMessageConsumer;
    stream:
      bindings:
        defaultBroadcastMessageConsumer-in-0:
          binder: rabbit
          destination: "web-defaultMessage"

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            listener: ERROR
            connection:
              CachingConnectionFactory: ERROR
      apache:
        kafka:
          clients: ERROR
          client:
            ClientUtils: ERROR
