server:
  port: 30090
  shutdown: graceful

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:30080
          predicates:
            - Path=/api/**
          filters:
            - JwtAuthenticationFilter
