server:
  port: 30090
  shutdown: graceful

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:30080
          filters:
            - name: JwtAuthenticationFilter
