server:
  port: 30080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_test
    username: root
    password: 102030
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
