server:
  port: 30120
  shutdown: graceful

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test_user
    password: test

  cloud:
    function:
      definition: defaultBroadcastMessageConsumer;
    stream:
      bindings:
        defaultBroadcastMessageConsumer-in-0:
          binder: rabbit
          destination: "web-defaultMessage"
