spring:
  datasource:
    url: jdbc:mysql://localhost:23306/local_db
    username: root
    password: 102030
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  rabbitmq:
#    host: localhost
#    port: 25672
#    username: test_user
#    password: test

  redis:
    host: localhost
    port: 26379

#  kafka:
#    bootstrap-servers: localhost:29092

