server:
  port: 30080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:23306/web_test
    username: root
    password: 102030
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  kafka:
    bootstrap-servers: kafka:9092

  redis:
    host: local-redis
    port: 26379

  rabbitmq:
    host: pos-rabbitmq
    port: 5672
    username: test_user
    password: test

  cloud:
    function:
      definition: defaultMessageProducer;
    stream:
      bindings:
        defaultMessageProducer-out-0:
          binder: rabbit
          destination: "web-defaultMessage"

login:
  key: "abcdefg"
  expire: 10


logging:
  level:
    org:
      apache:
        kafka:
          clients: ERROR
          client:
            ClientUtils: ERROR
