server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    instance:
      prefer-ip-address: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

