spring:
  application:
    name: GatewayService

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:30080
          filters:
            - name: JwtAuthenticationFilter

        - id: login_route
          predicates:
            - Path=/login
          uri: http://localhost:30080

        - id: coupon_route
          predicates:
            - Path=/coupon/**
          uri: http://localhost:30080

info:
  auth: http://localhost:30100

secret:
  key: "967869b7-56b8-4766-8473-7baa04a499ab"
  header: "X-Gateway-Auth"

server:
  port: 30090
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: docker

  application:
    name: GatewayDockerService

  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:8081
          filters:
            - name: JwtAuthenticationFilter

        - id: login_route
          predicates:
            - Path=/login
          uri: http://localhost:8081

        - id: coupon_route
          predicates:
            - Path=/coupon/**
          uri: lb://DISCOVERYWEBAPISERVICE
          filters:
            - name: CustomLoadBalancerFilter

  info:
    auth: http://localhost:30100

  secret:
    key: "967869b7-56b8-4766-8473-7baa04a499ab"
    header: "X-Gateway-Auth"
  data:
    redis:
      host: localhost
      port: 26379

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    preferIpAddress: true


server:
  port: 30091
  shutdown: graceful

#logging:
#  level:
#    root: debug
