server:
  port: 30090
  shutdown: graceful

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:30080
          filters:
            - name: JwtAuthenticationFilter

        - id: login_route
          predicates:
            - Path=/login
          uri: http://localhost:30080

        - id: coupon_route
          predicates:
            - Path=/coupon/**
          uri: http://localhost:30080

info:
  auth: http://localhost:30100

secret:
  key: "967869b7-56b8-4766-8473-7baa04a499ab"
  header: "X-Gateway-Auth"
