spring:
  application:
    name: GatewayService

  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:30080
          filters:
            - name: JwtAuthenticationFilter

        - id: login_route
          predicates:
            - Path=/login
          uri: http://localhost:30080

        - id: coupon_route_with_userId
          predicates:
            - Path=/coupon/**
            - Query=userId
          uri: http://localhost:30080
          filters:
            - name: QueueHandlingFilter

        - id: coupon_route
          predicates:
            - Path=/coupon/**
          uri: http://localhost:30080



  data:
    redis:
      host: localhost
      port: 26379

info:
  auth: http://localhost:30100

secret:
  key: "967869b7-56b8-4766-8473-7baa04a499ab"
  header: "X-Gateway-Auth"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    preferIpAddress: true

server:
  port: 30090
  shutdown: graceful

logging:
  level:
    com.example.gateway.filter: INFO
---
spring:
  config:
    activate:
      on-profile: docker

  application:
    name: GatewayDockerService

  cloud:
    gateway:
      routes:
        - id: api_route
          predicates:
            - Path=/api/**
          uri: http://localhost:8081
          filters:
            - name: JwtAuthenticationFilter

        - id: login_route
          predicates:
            - Path=/login
          uri: http://localhost:8081

        ##################################################################
        # api rate limiter endpoints
        ##################################################################
        - id: coupon_route
          predicates:
            - Path=/coupon/**
          uri: lb://DISCOVERYWEBAPISERVICE
#          filters:
#            - name: CustomLoadBalancerFilter
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5  # 초당 5개의 요청을 허용
                redis-rate-limiter.burstCapacity: 10 # 최대 버스트 용량
                key-resolver: "#{@userKeyResolver}"   # KeyResolver 설정

        - id: coupon_route_with_userId
          uri: lb://DISCOVERYWEBAPISERVICE
          predicates:
            - Path=/coupon/**
            - Query=userId
          filters:
            - name: QueueHandlingFilter

  info:
    auth: http://localhost:30100

  secret:
    key: "967869b7-56b8-4766-8473-7baa04a499ab"
    header: "X-Gateway-Auth"
  data:
    redis:
      host: localhost
      port: 26379

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    preferIpAddress: true


server:
  port: 30091
  shutdown: graceful

#logging:
#  level:
#    root: debug
